# -*- coding: utf-8 -*-
"""Thompson_scraper_holder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hZ9BiOEI2FMzCwvvVvLqJx2ipMH5qdDb
"""

import requests
from bs4 import BeautifulSoup
import csv
import pandas as pd
import json

def scrape_major_and_institutional_holders(stock_symbols):
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'}

    data = []

    for symbol in stock_symbols:
        url = f'https://finance.yahoo.com/quote/{symbol}/holders?p={symbol}'
        r = requests.get(url, headers=headers)

        if r.status_code == 200:
            soup = BeautifulSoup(r.text, 'html.parser')

            # Scrape major holders
            major_holders = [item.text.strip() for item in soup.find_all('td', class_='Ta(start)')]
            major_holders_data = {
                'Major Holders1': major_holders[0],
                'Major Holders2': major_holders[1],
                'Major Holders3': major_holders[2],
                'Major Holders4': major_holders[3],
            }

            # Scrape top institutional holders
            institutional_holders = [item.text.strip() for item in soup.find_all('td', class_='Ta(start)')]
            institutional_holders_data = {
                f'Top Institutional Holder{i+1}': institutional_holders[4+i] for i in range(10)
            }

            # Scrape percentages
            percentages = [item.text.strip() for item in soup.find_all('td', class_='Py(10px) Ta(start)')]
            percentages_data = {}
            if len(percentages) >= 3:
                percentages_data = {
                    'Shares Held by All Insider': percentages[0],
                    'Shares Held by Institutions': percentages[1],
                    'Float Held by Institutions': percentages[2],
                }

            # Scrape number of institutions holding shares
            num_institutions = soup.find('td', string='Number of Institutions Holding Shares')
            num_institutions_data = {'Number of Institutions Holding Shares': num_institutions.find_next('td').text.strip() if num_institutions else None}

            data.append({
                'stock_name': soup.find('h1').text.split('(')[0].strip(),
                **percentages_data,
                **major_holders_data,
                **institutional_holders_data,
                **num_institutions_data
            })

    return data

# Stock symbols
stock_symbols = ['TSLA', 'AAPL', 'GOOG', 'AMZN', 'META', 'INTC']

# Scrape major holders, top institutional holders, and percentages
holder_data = scrape_major_and_institutional_holders(stock_symbols)

# Exporting to JSON
JSON_FILE_PATH = 'Thompson_stock_holder_data.json'
with open(JSON_FILE_PATH, 'w', encoding='utf-8') as jsonfile:
    json.dump(holder_data, jsonfile, indent=4)

# Exporting to CSV
CSV_FILE_PATH = 'Thompson_stock_holder_data.csv'
with open(CSV_FILE_PATH, 'w', newline='', encoding='utf-8') as csvfile:
    fieldnames = ['stock_name', 'Shares Held by All Insider', 'Shares Held by Institutions', 'Float Held by Institutions',
                  'Major Holders1', 'Major Holders2', 'Major Holders3', 'Major Holders4',
                  'Top Institutional Holder1', 'Top Institutional Holder2', 'Top Institutional Holder3',
                  'Top Institutional Holder4', 'Top Institutional Holder5', 'Top Institutional Holder6',
                  'Top Institutional Holder7', 'Top Institutional Holder8', 'Top Institutional Holder9',
                  'Top Institutional Holder10', 'Number of Institutions Holding Shares']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(holder_data)

# Exporting to Excel
EXCEL_FILE_PATH = 'Thompson_stock_holder_data.xlsx'
df = pd.DataFrame(holder_data)
df.to_excel(EXCEL_FILE_PATH, index=False)

print("Holders information has been exported successfully to JSON, CSV, and Excel files.")

from google.colab import files

# Download Excel file
files.download('Thompson_stock_holder_data.xlsx')

# Download CSV file
files.download('Thompson_stock_holder_data.csv')

# Download JSON file
files.download('Thompson_stock_holder_data.json')